# Generated by Django 3.0.7 on 2020-06-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20200614_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('englishg', 'ENGLISH'), ('german', 'GERMAN')], max_length=10),
        ),
    ]
